name: CD

on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker image
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/vcnotify:latest
          docker build -t "$IMAGE" .

      - name: Push Docker image
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/vcnotify:latest
          docker push "$IMAGE"
