name: CD

# main ブランチへのプッシュでトリガー
on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # リポジトリチェックアウト
      - uses: actions/checkout@v3

      # GHCR へのログイン
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      # イメージのビルドとタグ付け
      - name: Build Docker image
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/vcnotify:latest
          docker build -t $IMAGE .

      # イメージを GHCR にプッシュ
      - name: Push Docker image
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/vcnotify:latest
          docker push $IMAGE
